name: Docker Image CI

on:
  push:
    branches: [ main, beta, features ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.mysql.buildx
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cryptopump_db:buildx-latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile.cryptopump
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cryptopump:latest

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile.mysql
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cryptopump_db:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}